function CodeDefine() { 
this.def = new Array();
this.def["NAMO_B"] = {file: "NAMO_c.html",line:35,type:"var"};
this.def["NAMO_DW"] = {file: "NAMO_c.html",line:38,type:"var"};
this.def["NAMO.c:NAMO_M_"] = {file: "NAMO_c.html",line:41,type:"var"};
this.def["NAMO_M"] = {file: "NAMO_c.html",line:42,type:"var"};
this.def["NAMO_step"] = {file: "NAMO_c.html",line:45,type:"fcn"};
this.def["NAMO_initialize"] = {file: "NAMO_c.html",line:102,type:"fcn"};
this.def["B_NAMO"] = {file: "NAMO_h.html",line:60,type:"type"};
this.def["DW_NAMO"] = {file: "NAMO_h.html",line:65,type:"type"};
this.def["ConstP_NAMO"] = {file: "NAMO_h.html",line:73,type:"type"};
this.def["RT_MODEL_NAMO"] = {file: "NAMO_types_h.html",line:37,type:"type"};
this.def["NAMO_ConstP"] = {file: "NAMO_data_c.html",line:35,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:42,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:66,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:77,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:101,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:42,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:66,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:41,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:42,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:43,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:44,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:45,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:46,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:52,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:64,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:70,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:76,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:98,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:52,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:59,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:66,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:79,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:80,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:81,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:93,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:98,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:103,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:110,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:117,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:124,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:131,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:138,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:145,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:163,type:"type"};
this.def["G_ADC_Conf"] = {file: "NAMO_ADC_c.html",line:35,type:"var"};
this.def["G_ADC_Handler"] = {file: "NAMO_ADC_c.html",line:38,type:"var"};
this.def["ADC1_RegularConvertedValue"] = {file: "NAMO_ADC_c.html",line:41,type:"var"};
this.def["ADC1_Conf"] = {file: "NAMO_ADC_c.html",line:44,type:"var"};
this.def["G_ADC1_PollTimeOut"] = {file: "NAMO_ADC_c.html",line:62,type:"var"};
this.def["ADC_ConfTypeDef"] = {file: "NAMO_ADC_h.html",line:55,type:"type"};
this.def["G_DAC_Conf"] = {file: "NAMO_DAC_c.html",line:35,type:"var"};
this.def["G_DAC_Handler"] = {file: "NAMO_DAC_c.html",line:38,type:"var"};
this.def["DAC_Conf"] = {file: "NAMO_DAC_c.html",line:41,type:"var"};
this.def["DAC_ConfTypeDef"] = {file: "NAMO_DAC_h.html",line:43,type:"type"};
this.def["main.c:OverrunFlags"] = {file: "main_c.html",line:38,type:"var"};
this.def["main.c:autoReloadTimerLoopVal_S"] = {file: "main_c.html",line:41,type:"var"};
this.def["remainAutoReloadTimerLoopVal_S"] = {file: "main_c.html",line:44,type:"var"};
this.def["main"] = {file: "main_c.html",line:52,type:"fcn"};
this.def["SysTick_Handler"] = {file: "stm32xxxx_it_c.html",line:34,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["NAMO_c.html"] = "../NAMO.c";
	this.html2Root["NAMO_c.html"] = "NAMO_c.html";
	this.html2SrcPath["NAMO_h.html"] = "../NAMO.h";
	this.html2Root["NAMO_h.html"] = "NAMO_h.html";
	this.html2SrcPath["NAMO_private_h.html"] = "../NAMO_private.h";
	this.html2Root["NAMO_private_h.html"] = "NAMO_private_h.html";
	this.html2SrcPath["NAMO_types_h.html"] = "../NAMO_types.h";
	this.html2Root["NAMO_types_h.html"] = "NAMO_types_h.html";
	this.html2SrcPath["NAMO_data_c.html"] = "../NAMO_data.c";
	this.html2Root["NAMO_data_c.html"] = "NAMO_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["NAMO_ADC_c.html"] = "../NAMO_ADC.c";
	this.html2Root["NAMO_ADC_c.html"] = "NAMO_ADC_c.html";
	this.html2SrcPath["NAMO_ADC_h.html"] = "../NAMO_ADC.h";
	this.html2Root["NAMO_ADC_h.html"] = "NAMO_ADC_h.html";
	this.html2SrcPath["NAMO_DAC_c.html"] = "../NAMO_DAC.c";
	this.html2Root["NAMO_DAC_c.html"] = "NAMO_DAC_c.html";
	this.html2SrcPath["NAMO_DAC_h.html"] = "../NAMO_DAC.h";
	this.html2Root["NAMO_DAC_h.html"] = "NAMO_DAC_h.html";
	this.html2SrcPath["NAMO_External_Functions_h.html"] = "../NAMO_External_Functions.h";
	this.html2Root["NAMO_External_Functions_h.html"] = "NAMO_External_Functions_h.html";
	this.html2SrcPath["STM32_Config_h.html"] = "../STM32_Config.h";
	this.html2Root["STM32_Config_h.html"] = "STM32_Config_h.html";
	this.html2SrcPath["main_c.html"] = "../main.c";
	this.html2Root["main_c.html"] = "main_c.html";
	this.html2SrcPath["stm32xxxx_it_c.html"] = "../stm32xxxx_it.c";
	this.html2Root["stm32xxxx_it_c.html"] = "stm32xxxx_it_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"NAMO_c.html","NAMO_h.html","NAMO_private_h.html","NAMO_types_h.html","NAMO_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","NAMO_ADC_c.html","NAMO_ADC_h.html","NAMO_DAC_c.html","NAMO_DAC_h.html","NAMO_External_Functions_h.html","STM32_Config_h.html","main_c.html","stm32xxxx_it_c.html"];
